<?php
    $dict=array(
        "Title0" => "ltr",


        "Title1" => "Basic Information",
        "Title2" => "Account Information",
        "Title3" => "Social Information",
        "Title4" => "your name",
        "Title5" => "Drop image here or click to upload.",
        "Title6" => "Upload your ID image here",
        "Title7" => "your birthday",
        "Title8" => "your place of birth",
        "Title9" => "your father's name",
        "Title10" => "your National Code",
        "Title11" => "Id",

        "Title12" => "Bank name",
        "Title13" => "account number",
        "Title14" => "card number",
        "Title15" => "Shaba number",

        "Title17" => "Address",
        "Title18" => "Postal code",
        "Title19" => "Mobile number",
        "Title20" => "Phone",
        "Title201" => "your email address",


        "Title21" => "Home",
        "Title22" => "About",
        "Title23" => "Services",
        "Title24" => "Project",
        "Title25" => "User",
        "Title26" => "username",
        "Title27" => "admin panel",
        "Title28" => "pages",
        "Title29" => "shop",


        "msgPlaceholder" => "file",
        "fileSingle" => "fileSingle",

        "Title31" => "Education",
        "Title32" => "events",
        "Title33" => "Professors",
        "Title34" => "Students",
        "Title35" => "Courses",
        "Title36" => "Library",
        "Title37" => "Departments",
        "Title38" => "Mailbox",


        "Title41" => "en",
        

        "continue" => "continue",
        "login" => "login",
        "phonenum" => "your number",
        "enterphonenum" => "enter your phone number",
        "pass" => "password",
        "logincode" => "enter your code",
        "activationcode" => "activation code sent successfully",



        "submit" => "submit",

        "hotline" => "hotline",
        "email" => "email",
        "adminpanel" => "ADMIN PANEL",
        "dashboard" => "Dashboard",
        "charts" => "Charts",
        "email" => "Email",
        "FAQ" => "FAQ",
        "profile" => "Profile",
        "tables" => "Tables",
        "invoice" => "Invoice",


        "Title80" => "asset",
        "Title81" => "icon",
        "Title82" => "1 month",
        "Title83" => "2 months",
        "Title84" => "6 months",
        "Title85" => "1 year",
        "Title86" => "Bitcoin(BTC)",
        "Title860" => "Ethereum(ETH)",
        "Title861" => "Tether(USDT)",
        "Title862" => "Binance Coin(BNB)",
        "Title863" => "Cardano(ADA)",
        "Title87" => "all",
        "Title88" => "high risk",
        "Title89" => "low risk",
        "Title89۰" => "medium risk",
        "Title90" => "assets table",
        "Title91" => "50%",
        "Title92" => "20%",
        "Title93" => "10%",
        "Title94" => "40%",
        "Title95" => "all assets",
        "Title96" => "favorits assets",
        "Title97" => "$300000000",
        "Title98" => "Funds table",
        "Title99" => "user's assets",
        "Title100" => "volume",
        "Title101" => "value",
        "Title102" => "Net invest",
        "Title103" => "risk",
        "Title104" => "low",
        "Title105" => "high",
        "Title106" => "medium",
        "Title107" => "price",



        "fundvalue" => "fund value",
        "efficiency" => "efficiency",
        "amonth" => "a month",
        "threemonths" => "2 months",
        "sixmonths" => "6 months",
        "ayear" => "a year",
        "assetsvolume" => "The current volume of user assets in the fund ",
        "assetsvalue" => "The value of the user's assets in the fund",
        "Profitandlosspercentage" => "Profit and loss percentage",
        "Durationofuserpresence" => "Duration of user presence",
        "assetsname" => "asset's name",
        "Percentageofassets" => "Percentage of assets",
        "Profitandlosspercentage" => "Profit and loss percentage",
        "entrydate" => "entry date",
        "Market" => "Market",
        "managers" => "managers",
        "funddescription" => "fund description",
        "funddescriptioncontent" => "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        "cashin" => "cash in",
        "Enterthedesiredamount" => "Enter the desired amount",
        "Enterthedesiredvolume" => "Enter the desired volume",
        "cashout" => "cash out",
        "transactionamount" => "Transaction amount",
        "Typeoftransaction" => "Type of transaction",
        "Transactionvolume"  => "Transaction volume",
        "Condition" => "Condition",
        "transactiondate" => "transaction date",
        "confirm" => "confirm",
        "cancel" => "cancel",
        "amountofuserassets" => "The amount of user assets in the fund",
        "Priceperunitoffund" => "Price per unit of fund",
        "Userassetvalue" => "User asset value",
        "viewallnotification" => "View All Notification",
        "notifications" => "Notifications",
        "activities" => "activities",
        "viewallactivities" => "view all activities",





        "fileSingle" => 'file',
        "filePlural" => 'files',
        "browseLabel" => 'Browse &hellip;',
        "removeLabel" => 'Remove',
        "removeTitle" => 'Clear selected files',
        "cancelLabel" => 'Cancel',
        "cancelTitle" => 'Abort ongoing upload',
        "pauseLabel" => 'Pause',
        "pauseTitle" => 'Pause ongoing upload',
        "uploadLabel" => 'Upload',
        "uploadTitle" => 'Upload selected files',
        "msgNo" => 'No',
        "msgNoFilesSelected" => 'No files selected',
        "msgPaused" => 'Paused',
        "msgCancelled" => 'Cancelled',
        "msgPlaceholder" => 'Select {files} ...',
        "msgZoomModalHeading" => 'Detailed Preview',
        "msgFileRequired" => 'You must select a file to upload.',
        "msgSizeTooSmall" => 'File \"{name}\" (<b>{size} KB</b>) is too small and must be larger than <b>{minSize} KB</b>.',
        "msgSizeTooLarge" => 'File \"{name}\" (<b>{size} KB</b>) exceeds maximum allowed upload size of <b>{maxSize} KB</b>.',
        "msgFilesTooLess" => 'You must select at least <b>{n}</b> {files} to upload.',
        "msgFilesTooMany"=> 'Number of files selected for upload <b>({n})</b> exceeds maximum allowed limit of <b>{m}</b>.',
        "msgTotalFilesTooMany" => 'You can upload a maximum of <b>{m}</b> files (<b>{n}</b> files detected).',
        "msgFileNotFound" => 'File \"{name}\" not found!',
        "msgFileSecured" => 'Security restrictions prevent reading the file \"{name}\".',
        "msgFileNotReadable" => 'File \"{name}\" is not readable.',
        "msgFilePreviewAborted" => 'File preview aborted for \"{name}\".',
        "msgFilePreviewError" => 'An error occurred while reading the file \"{name}\".',
        "msgInvalidFileName" => 'Invalid or unsupported characters in file name \"{name}\".',
        "msgInvalidFileType" => 'Invalid type for file \"{name}\". Only \"{types}\" files are supported.',
        "msgInvalidFileExtension" => 'Invalid extension for file \"{name}\". Only \"{extensions}\" files are supported.',
        'image'=> 'image',
        'html'=> 'HTML',
        'text'=> 'text',
        'video'=> 'video',
        'audio'=> 'audio',
        'flash'=> 'flash',
        'pdf'=> 'PDF',
        'object'=> 'object',
        "msgUploadAborted" => 'The file upload was aborted',
        "msgUploadThreshold" => 'Processing &hellip;',
        "msgUploadBegin" => 'Initializing &hellip;',
        "msgUploadEnd" => 'Done',
        "msgUploadResume" => 'Resuming upload &hellip;',
        "msgUploadEmpty" => 'No valid data available for upload.',
        "msgUploadError" => 'Upload Error',
        "msgDeleteError" => 'Delete Error',
        "msgProgressError" => 'Error',
        "msgValidationError" => 'Validation Error',
        "msgLoading" => 'Loading file {index} of {files} &hellip;',
        "msgProgress" => 'Loading file {index} of {files} - {name} - {percent}% completed.',
        "msgSelected" => '{n} {files} selected',
        "msgFoldersNotAllowed" => 'Drag & drop files only! Skipped {n} dropped folder(s).',
        "msgImageWidthSmall" => 'Width of image file \"{name}\" must be at least {size} px.',
        "msgImageHeightSmall" => 'Height of image file \"{name}\" must be at least {size} px.',
        "msgImageWidthLarge" => 'Width of image file \"{name}\" cannot exceed {size} px.',
        "msgImageHeightLarge" => 'Height of image file \"{name}\" cannot exceed {size} px.',
        "msgImageResizeError" => 'Could not get the image dimensions to resize.',
        "msgImageResizeException" => 'Error while resizing the image.<pre>{errors}</pre>',
        "msgAjaxError" => 'Something went wrong with the {operation} operation. Please try again later!',
        "msgAjaxProgressError" => '{operation} failed',
        "msgDuplicateFile" => 'File \"{name}\" of same size "{size} KB" has already been selected earlier. Skipping duplicate selection.',
        "msgResumableUploadRetriesExceeded" =>  'Upload aborted beyond <b>{max}</b> retries for file <b>{file}</b>! Error Details: <pre>{error}</pre>',
        "msgPendingTime" => '{time} remaining',
        "msgCalculatingTime" => 'calculating time remaining',
        "deleteThumb" => 'file delete',
        "uploadThumb" => 'file upload',
        "uploadBatch" => 'batch file upload',
        "uploadExtra" => 'form data upload',
        "dropZoneTitle" => 'Drag & drop files here &hellip;',
        "dropZoneClickTitle" => '<br>(or click to select {files})',
        "removeTitle" => 'Remove file',
        "uploadTitle" => 'Upload file',
        "uploadRetryTitle" => 'Retry upload',
        "downloadTitle" => 'Download file',
        "zoomTitle" => 'View details',
        "dragTitle" => 'Move / Rearrange',
        "indicatorNewTitle" => 'Not uploaded yet',
        "indicatorSuccessTitle" => 'Uploaded',
        "indicatorErrorTitle" => 'Upload Error',
        "indicatorPausedTitle" => 'Upload Paused',
        "indicatorLoadingTitle" =>  'Uploading &hellip;',
        "prev" => 'View previous file',
        "next" => 'View next file',
        "toggleheader" => 'Toggle header',
        "fullscreen" => 'Toggle full screen',
        "borderless" => 'Toggle borderless mode',
        "close" => 'Close detailed preview',



        "IDPic" => "ID picture" ,
        "NotePic" => "National card photo",
        "CardPic" => "Bank Card picture",

        "exit" => "exit"
    );
?>