<?php

    $dict=array(
        "Title0" => "rtl",



        "continue" => "ادامه",
        "login" => "ورود",
        "phonenum" => "شماره تلفن همراه",
        "enterphonenum" => "شماره خود را وارد کنید",
        "pass" => "رمز عبور",
        "logincode" => "کد ارسال شده را وارد کنید",
        "activationcode" => "کد فعالسازی با موفقیت ارسال شد",

        "hotline" => "شماره تماس",
        "email" => "ایمیل",

        "submit" => "ثبت",


        "adminpanel" => "پنل مدیریت",
        "dashboard" => "داشبورد",
        "charts" => "نمودار ها",
        "email" => "ایمیل",
        "FAQ" => "سوالات متداول",
        "profile" => "پروفایل",
        "tables" => "جدول ها",
        "invoice" => "صورت حساب",


        "Title1" => "اطلاعات شخصی",
        "Title2" => "اطلاعات مالی",
        "Title3" => "اطلاعات ارتباطی",
        "Title4" => "نام و نام خانوادگی",
        "Title5" => "تصویر را اینجا رها کنید یا برای بارگذاری کلیک کنید.",
        "Title6" => "تصویر کارت ملی خود را در این قسمت بارگذاری کنید",
        "Title7" => "تاریخ تولد",
        "Title8" => "محل تولد",
        "Title9" => "نام پدر",
        "Title10" => "کد ملی",
        "Title11" => "شماره شناسنامه",

        "Title12" => "نام بانک",
        "Title13" => "شماره حساب",
        "Title14" => "شماره کارت",
        "Title15" => "شماره شبا",

        "Title17" => "آدرس",
        "Title18" => "کدپستی",
        "Title19" => "شماره همراه",
        "Title20" => "تلفن ثابت",
        "Title201" => "ایمیل",

        "Title21" => "خانه",
        "Title22" => "درباره ما",
        "Title23" => "خدمات",
        "Title24" => "پروژه ها",
        "Title25" => "کاربر",
        "Title26" => "نام کاربری",
        "Title27" => "پنل ادمین",
        "Title28" => "صفحات",
        "Title29" => "فروشگاه",



        "Title31" => "آموزش",
        "Title32" => "رویداد ها",
        "Title33" => "اساتید",
        "Title34" => "دانشجویان",
        "Title35" => "دوره ها",
        "Title36" => "کتابخانه",
        "Title37" => "دپارتمان ها",
        "Title38" => "صندوق پستی",


        "Title41" => "fa",

        "msgPlaceholder" => "فایل",
        "fileSingle" => "فااایل",



        "Title80" => "دارایی",
        "Title81" => "آیکون",
        "Title82" => "بازدهی ۱ ماه",
        "Title83" => "بازدهی ۲ ماه",
        "Title84" => "بازدهی ۶ ماه",
        "Title85" => "بازدهی ۱ سال",
        "Title86" => " بیت کوین (BTC)",
        "Title860" => " اتریوم (ETH)",
        "Title861" => "تتر (USDT)",
        "Title862" => "بایننس کوین (BNB)",
        "Title863" => "کاردانو (ADA)",
        "Title87" => "نمایش همه",
        "Title88" => "ریسک بالا",
        "Title89" => "ریسک پایین",
        "Title890" => "ریسک متوسط",
        "Title90" => "جدول دارایی ها",
        "Title91" => "۵۰٪",
        "Title92" => "۲۰٪",
        "Title93" => "۱۰٪",
        "Title94" => "۴۰٪",
        "Title95" => "همه",
        "Title96" => "علاقه مندی ها",
        "Title97" => "$3000000",
        "Title98" => "جدول صندوق ها",
        "Title99" => "دارایی های کاربر",
        "Title100" => "حجم دارایی موجود",
        "Title101" => "ارزش روز",
        "Title102" => "خالص سرمایه گذاری",
        "Title103" => "ریسک",
        "Title104" => "کم",
        "Title105" => "زیاد",
        "Title106" => "متوسط",
        "Title107" => "قیمت",



        "fundvalue" => "ارزش صندوق",
        "efficiency" => " بازدهی صندوق",
        "amonth" => "یک ماه",
        "threemonths" => "دو ماه",
        "sixmonths" => "شش ماه",
        "ayear" => "یک سال",
        "assetsvolume" => "حجم فعلی دارایی یوزر در صندوق ",
        "assetsvalue" => "ارزش دارایی یوزر در صندوق",
        "Profitandlosspercentage" => "درصد سود و زیان یوزر در صندوق",
        "Durationofuserpresence" => "عمر حضور یوزر در صندوق",
        "assetsname" => "نام دارایی",
        "Percentageofassets" => "درصد دارایی",
        "Profitandlosspercentage" => "درصد سود و زیان",
        "entrydate" => "تاریخ ورود",
        "Market" => "بازار",
        "managers" => "مدیران",
        "funddescription" => "توضیحات صندوق",
        "funddescriptioncontent" => "لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای زیادی در شصت و سه درصد گذشته، حال و آینده شناخت فراوان جامعه و متخصصان را می طلبد تا با نرم افزارها شناخت بیشتری را برای طراحان رایانه ای علی الخصوص طراحان خلاقی و فرهنگ پیشرو در زبان فارسی ایجاد کرد. در این صورت می توان امید داشت که تمام و دشواری موجود در ارائه راهکارها و شرایط سخت تایپ به پایان رسد وزمان مورد نیاز شامل حروفچینی دستاوردهای اصلی و جوابگوی سوالات پیوسته اهل دنیای موجود طراحی اساسا مورد استفاده قرار گیرد.",
        "cashin" => " ورود سرمایه",
        "Enterthedesiredamount" => "مبلغ مورد نظر را وارد کنید",
        "Enterthedesiredvolume" => "حجم مورد نظر را وارد کنید",
        "cashout" => "خروج سرمایه",
        "transactionamount" => "مبلغ تراکنش",
        "Typeoftransaction" => "نوع تراکنش",
        "Transactionvolume"  => "حجم تراکنش",
        "Condition" => "وضعیت",
        "transactiondate" => "تاریخ تراکنش",
        "confirm" => "تایید",
        "cancel" => "انصراف",
        "amountofuserassets" => "حجم دارایی یوزر در صندوق",
        "Priceperunitoffund" => "قیمت هر واحد صندوق",
        "Userassetvalue" => "ارزش دارایی یوزر",
        "viewallnotification" => "نمایش همه ی اعلان ها",
        "notifications" => "اعلان ها",
        "activities" => "فعالیت ها",
        "viewallactivities" => "نمایش همه ی فعالیت ها",

        "exit" => "خروج",

        


        "fileSingle" => 'فایل',
        "filePlural" => 'فایل‌ها',
        "browseLabel" => 'انتخاب &hellip;',
        "removeLabel" => 'حذف',
        "removeTitle" => 'پاکسازی فایل‌های انتخاب شده',
        "cancelLabel" => 'لغو',
        "cancelTitle" => 'لغو بارگزاری جاری',
        "pauseLabel" => 'Pause',
        "pauseTitle" => 'Pause ongoing upload',
        "uploadLabel" => 'بارگذاری',
        "uploadTitle" => 'بارگذاری فایل‌های انتخاب شده',
        "msgNo" => 'نه',
        "msgNoFilesSelected" => 'هیچ فایلی انتخاب نشده است',
        "msgPaused" => 'Paused',
        "msgCancelled" => 'لغو شد',
        "msgPlaceholder" => 'انتخاب {files} ...',
        "msgZoomModalHeading" => 'نمایش با جزییات',
        "msgFileRequired" => 'شما باید یک فایل برای بارگذاری انتخاب نمایید.',
        "msgSizeTooSmall" => 'فایل \"{name}\" (<b>{size} کیلوبایت</b>) خیلی کوچک است و باید از <b>{minSize} کیلوبایت بزرگتر باشد</b>.',
        "msgSizeTooLarge" => 'فایل \"{name}\" (<b>{size} کیلوبایت</b>) از حداکثر مجاز <b>{maxSize} کیلوبایت</b> بزرگتر است.',
        "msgFilesTooLess" => 'شما باید حداقل <b>{n}</b> {files} فایل برای بارگذاری انتخاب کنید.',
        "msgFilesTooMany"=> 'تعداد فایل‌های انتخاب شده برای بارگذاری <b>({n})</b> از حداکثر مجاز عبور کرده است <b>{m}</b>.',
        "msgTotalFilesTooMany" => 'You can upload a maximum of <b>{m}</b> files (<b>{n}</b> files detected).',
        "msgFileNotFound" => 'فایل \"{name}\" یافت نشد!',
        "msgFileSecured" => 'محدودیت های امنیتی مانع خواندن فایل \"{name}\" است.',
        "msgFileNotReadable" => 'فایل \"{name}\" قابل نوشتن نیست.',
        "msgFilePreviewAborted" => 'پیش نمایش فایل \"{name}\". به مشکل خورد',
        "msgFilePreviewError" => 'در هنگام خواندن فایل \"{name}\" خطایی رخ داد.',
        "msgInvalidFileName" => 'کاراکترهای غیرمجاز و یا ناشناخته در نام فایل \"{name}\".',
        "msgInvalidFileType" => 'نوع فایل \"{name}\" معتبر نیست. فقط \"{types}\" پشیبانی می‌شوند.',
        "msgInvalidFileExtension" => 'پسوند فایل \"{name}\" معتبر نیست. فقط \"{extensions}\" پشتیبانی می‌شوند.',
        'image'=> 'عکس',
        'html'=> 'اچ تی ام ال',
        'text'=> 'متن',
        'video'=> 'ویدئو',
        'audio'=> 'صدا',
        'flash'=> 'فلش',
        'pdf'=> 'پی دی اف',
        'object'=> 'دیگر',
        "msgUploadAborted" => 'بارگذاری فایل به مشکل خورد.',
        "msgUploadThreshold" => 'در حال پردازش &hellip;',
        "msgUploadBegin" => 'در حال شروع &hellip;',
        "msgUploadEnd" => 'انجام شد',
        "msgUploadResume" => 'Resuming upload &hellip;',
        "msgUploadEmpty" => 'هیچ داده معتبری برای بارگذاری موجود نیست.',
        "msgUploadError" => 'Upload Error',
        "msgDeleteError" => 'Delete Error',
        "msgProgressError" => 'Error',
        "msgValidationError" => 'خطای اعتبار سنجی',
        "msgLoading" => 'بارگیری فایل {index} از {files} &hellip;',
        "msgProgress" => 'بارگیری فایل {index} از {files} - {name} - {percent}% تمام شد.',
        "msgSelected" => '{n} {files} انتخاب شده',
        "msgFoldersNotAllowed" => 'فقط فایل‌ها را بکشید و رها کنید! {n} پوشه نادیده گرفته شد.',
        "msgImageWidthSmall" => 'عرض فایل تصویر \"{name}\" باید حداقل {size} پیکسل باشد.',
        "msgImageHeightSmall" => 'ارتفاع فایل تصویر \"{name}\" باید حداقل {size} پیکسل باشد.',
        "msgImageWidthLarge" => 'عرض فایل تصویر \"{name}\" نمیتواند از {size} پیکسل بیشتر باشد.',
        "msgImageHeightLarge" => 'ارتفاع فایل تصویر \"{name}\" نمی‌تواند از {size} پیکسل بیشتر باشد.',
        "msgImageResizeError" => 'یافت نشد ابعاد تصویر را برای تغییر اندازه.',
        "msgImageResizeException" => 'خطا در هنگام تغییر اندازه تصویر.<pre>{errors}</pre>',
        "msgAjaxError" => 'به نظر مشکلی در حین {operation} روی داده است. لطفا دوباره تلاش کنید!',
        "msgAjaxProgressError" => '{operation} لغو شد',
        "msgDuplicateFile" => 'File \"{name}\" of same size \"{size} KB\" has already been selected earlier. Skipping duplicate selection.',
        "msgResumableUploadRetriesExceeded" =>  'Upload aborted beyond <b>{max}</b> retries for file <b>{file}</b>! Error Details: <pre>{error}</pre>',
        "msgPendingTime" => '{time} remaining',
        "msgCalculatingTime" => 'calculating time remaining',
        "deleteThumb" => 'حذف فایل',
        "uploadThumb" => 'بارگذاری فایل',
        "uploadBatch" => 'بارگذاری جمعی فایلها',
        "uploadExtra" => 'بارگذاری با کمک فُرم',
        "dropZoneTitle" => 'فایل‌ها را بکشید و در اینجا رها کنید &hellip;',
        "dropZoneClickTitle" => '<br>(یا برای انتخاب {files} کلیک کنید)',
        "removeTitle" => 'حذف فایل',
        "uploadTitle" => 'آپلود فایل',
        "uploadRetryTitle" => 'بارگیری مجدد',
        "downloadTitle" => 'دریافت فایل',
        "zoomTitle" => 'دیدن جزئیات',
        "dragTitle" => 'جابجایی / چیدمان',
        "indicatorNewTitle" => 'آپلود نشده است',
        "indicatorSuccessTitle" => 'آپلود شده',
        "indicatorErrorTitle" => 'بارگذاری خطا',
        "indicatorPausedTitle" => 'Upload Paused',
        "indicatorLoadingTitle" =>  'آپلود &hellip;',
        "prev" => 'مشاهده فایل قبلی',
        "next" => 'مشاهده فایل بعدی',
        "toggleheader" => 'نمایش عنوان',
        "fullscreen" => 'نمایش تمام صفحه',
        "borderless" => 'نمایش حاشیه',
        "close" => 'بستن نمایش با جزییات',


        "IDPic" => "تصویر شناسنامه" ,
        "NotePic" => "تصویز کارت ملی",
        "CardPic" => "تصویر کارت بانکی",
        
        
    );
?>